### ISSUE TITLE
Unable to load argon2-ffi library on node 6.12.2

### ISSUE THREAD

**Issue by codingchili** [cjlarose/argon2-ffi#27]
Hello,

I am having issues loading this library on Node 6.12.2, tested working fine in Node 6.11.1 and 8.11.2.

6.12.2. is an LTS release used by Kibana 6+, this leads to my plugin not being able to start successfully in recent versions.  https://github.com/codingchili/kbn-authentication-plugin

Here is a link to the 6.12.2 release: https://nodejs.org/en/blog/release/v6.12.2/

Stack trace when running the reproducer
```
C:\Program Files\Kibana\node\node_modules\bindings\bindings.js:88
        throw e
        ^

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Program Files\Kibana\node\node_modules\ref-napi\build\Release\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (C:\Program Files\Kibana\node\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (C:\Program Files\Kibana\node\node_modules\ref-napi\lib\ref.js:7:47)
    at Module._compile (module.js:570:32)
```

Please see the attached reproducer, unzip and run with:
```
npm install
node index.js
```

[reproducer.zip](https://github.com/cjlarose/argon2-ffi/files/2081805/reproducer.zip)

Thanks!

Ps. Thanks for providing argon2 for node :fire:

**Comment by cjlarose** [comment]
@codingchili Do you know if this is still an active problem for you on the latest version?

**Comment by codingchili** [comment]
I'm not running 6.12.2 anymore, but I'll try it with the reproducer to see if it's fixed. Sometime next week.

**Comment by codingchili** [comment]
Same error using 1.1.2 and 6.12.2 on windows. works on linux.

Node 6.X is reaching end of life in April.

**Comment by cjlarose** [comment]
Closing this since Node 6 is now EOL.

Supported versions of Node are 10.x and 12.x at the time of writing

https://nodejs.org/en/about/releases/
