### ISSUE TITLE
Unable to npm install argon2-ffi 

### ISSUE THREAD

**Issue by mradkov** [cjlarose/argon2-ffi#38]
Trying to instal argon2-ffi in an emtpy project results in this:

Node: v10.14.2
Npm: 6.4.1

> $ npm install --save argon2-ffi
> 
> 
> > ref-napi@1.4.1 install /Users/xxx/my-project/node_modules/ref-napi
> > node-gyp rebuild
> 
> gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
> gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
> gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
>   CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
>   LIBTOOL-STATIC Release/nothing.a
> Traceback (most recent call last):
>   File "./gyp-mac-tool", line 611, in <module>
>     sys.exit(main(sys.argv[1:]))
>   File "./gyp-mac-tool", line 28, in main
>     exit_code = executor.Dispatch(args)
>   File "./gyp-mac-tool", line 43, in Dispatch
>     return getattr(self, method)(*args[1:])
>   File "./gyp-mac-tool", line 246, in ExecFilterLibtool
>     if not libtool_re.match(line) and not libtool_re5.match(line):
> TypeError: cannot use a string pattern on a bytes-like object
> make: *** [Release/nothing.a] Error 1
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/Users/xxx/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
> gyp ERR! System Darwin 18.2.0
> gyp ERR! command "/Users/xxx/.nvm/versions/node/v10.14.2/bin/node" "/Users/xxx/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/xxx/my-project/node_modules/ref-napi
> gyp ERR! node -v v10.14.2
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm WARN sass-loader@5.0.1 requires a peer of webpack@^2.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN The package node-sass is included as both a dev and production dependency.
> npm WARN The package sass-loader is included as both a dev and production dependency.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ref-napi@1.4.1 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ref-napi@1.4.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/xxx/.npm/_logs/2019-04-08T16_49_21_033Z-debug.log

**Comment by cjlarose** [comment]
This looks like an error occurring when running something in Python.

What do you get when you run

```
python --version
```

What OS are you using?

**Comment by mradkov** [comment]
> ```
> python --version
> ```

 Python 3.7.0a1


> What OS are you using?

macOS Mojave 10.14.3

**Comment by cjlarose** [comment]
I think this problem might be related to the fact that `python` on your `PATH` runs Python 3 instead of Python 2. I'm also running macOS Mojave 10.14.3. On a fresh macOS system, `python` refers to `/usr/bin/python`, which is Python 2.7.10.

I'd expect most other projects that use `node-gyp` in their build system to also fail for systems configured like your own.

I recommend you make it so that when you invoke the `python` command, it executes Python 2. If you want to run Python 3 also, I suggest running making it so that it requires you to run the `python3` command.

**Comment by mradkov** [comment]
I tried changing the `PATH` to run python 2 with the `python` alias. I got the same error while trying to install the package.

Update: Removing python3 and updating all symlinks to point to the default 2.7.10 `python` version did the job. Thanks.
