### ISSUE TITLE
importing argon2-ffi crashes node 14

### ISSUE THREAD

**Issue by twelve17** [cjlarose/argon2-ffi#56]
I believe the root cause is https://github.com/node-ffi-napi/node-ffi-napi/issues/71 .  According [to this comment](https://github.com/node-ffi-napi/node-ffi-napi/issues/71#issuecomment-651407679), this has been fixed in node-ffi-nap v3.x.

Is it possible to update the dependency in this project?

**Comment by cjlarose** [comment]
I'm able to reproduce this on macOS on Node 14.15.1. I'll try upgrading to `ffi-napi` 3.x

**Comment by cjlarose** [comment]
`argon2-ffi` version 2.0.0 is published and includes a fix for this issue. Thanks for reporting it and let me know if it works for you!

**Comment by twelve17** [comment]
@cjlarose  Thanks so much for the quick response!

Ok, I am testing it out now. I'm occasionally running into a segfault, but I am guessing it has to do with the ffi-api lib more than with this library.  I'm going to post on the linked issue and see if I can get more info.

**Comment by twelve17** [comment]
@cjlarose Since my above comment, I cleared my `node_modules` and nuked my `package-lock.json`, and have not gotten any crashes since. Thanks again!

**Comment by cjlarose** [comment]
Happy to help!
